---
-  hosts: testServer
   remote_user: ec2-user
   tasks:
   
      - name: Install httpd package
        yum: name=httpd state=latest
        become: yes
        
      - name: Starting httpd service
        service: name=httpd state=started
        become: yes
        